"""empty message

Revision ID: 9e8415f7ba23
Revises: ee8bb4fb09df
Create Date: 2024-07-29 23:08:07.747157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e8415f7ba23'
down_revision: Union[str, None] = 'ee8bb4fb09df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lectures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('topic', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lectures_difficulty'), 'lectures', ['difficulty'], unique=False)
    op.create_index(op.f('ix_lectures_id'), 'lectures', ['id'], unique=False)
    op.create_index(op.f('ix_lectures_title'), 'lectures', ['title'], unique=False)
    op.create_index(op.f('ix_lectures_topic'), 'lectures', ['topic'], unique=False)
    op.create_table('tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_level', sa.Integer(), nullable=True),
    sa.Column('grow', sa.String(), nullable=True),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.Column('theme', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tests_grow'), 'tests', ['grow'], unique=False)
    op.create_index(op.f('ix_tests_id'), 'tests', ['id'], unique=False)
    op.create_index(op.f('ix_tests_purpose'), 'tests', ['purpose'], unique=False)
    op.create_table('comprehension_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lecture_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('conversation', sa.Text(), nullable=True),
    sa.Column('options', sa.Text(), nullable=True),
    sa.Column('answer', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['lecture_id'], ['lectures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comprehension_tasks_answer'), 'comprehension_tasks', ['answer'], unique=False)
    op.create_index(op.f('ix_comprehension_tasks_content'), 'comprehension_tasks', ['content'], unique=False)
    op.create_index(op.f('ix_comprehension_tasks_conversation'), 'comprehension_tasks', ['conversation'], unique=False)
    op.create_index(op.f('ix_comprehension_tasks_id'), 'comprehension_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_comprehension_tasks_lecture_id'), 'comprehension_tasks', ['lecture_id'], unique=False)
    op.create_index(op.f('ix_comprehension_tasks_options'), 'comprehension_tasks', ['options'], unique=False)
    op.create_index(op.f('ix_comprehension_tasks_question'), 'comprehension_tasks', ['question'], unique=False)
    op.create_table('writing_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lecture_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lecture_id'], ['lectures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_writing_tasks_content'), 'writing_tasks', ['content'], unique=False)
    op.create_index(op.f('ix_writing_tasks_id'), 'writing_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_writing_tasks_lecture_id'), 'writing_tasks', ['lecture_id'], unique=False)
    op.create_index(op.f('ix_writing_tasks_question'), 'writing_tasks', ['question'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_writing_tasks_question'), table_name='writing_tasks')
    op.drop_index(op.f('ix_writing_tasks_lecture_id'), table_name='writing_tasks')
    op.drop_index(op.f('ix_writing_tasks_id'), table_name='writing_tasks')
    op.drop_index(op.f('ix_writing_tasks_content'), table_name='writing_tasks')
    op.drop_table('writing_tasks')
    op.drop_index(op.f('ix_comprehension_tasks_question'), table_name='comprehension_tasks')
    op.drop_index(op.f('ix_comprehension_tasks_options'), table_name='comprehension_tasks')
    op.drop_index(op.f('ix_comprehension_tasks_lecture_id'), table_name='comprehension_tasks')
    op.drop_index(op.f('ix_comprehension_tasks_id'), table_name='comprehension_tasks')
    op.drop_index(op.f('ix_comprehension_tasks_conversation'), table_name='comprehension_tasks')
    op.drop_index(op.f('ix_comprehension_tasks_content'), table_name='comprehension_tasks')
    op.drop_index(op.f('ix_comprehension_tasks_answer'), table_name='comprehension_tasks')
    op.drop_table('comprehension_tasks')
    op.drop_index(op.f('ix_tests_purpose'), table_name='tests')
    op.drop_index(op.f('ix_tests_id'), table_name='tests')
    op.drop_index(op.f('ix_tests_grow'), table_name='tests')
    op.drop_table('tests')
    op.drop_index(op.f('ix_lectures_topic'), table_name='lectures')
    op.drop_index(op.f('ix_lectures_title'), table_name='lectures')
    op.drop_index(op.f('ix_lectures_id'), table_name='lectures')
    op.drop_index(op.f('ix_lectures_difficulty'), table_name='lectures')
    op.drop_table('lectures')
    # ### end Alembic commands ###
