"""empty message

Revision ID: bfd988156b51
Revises: fd555cac3a5e
Create Date: 2024-07-31 18:30:54.770011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfd988156b51'
down_revision: Union[str, None] = 'fd555cac3a5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voca_id'), 'voca', ['id'], unique=False)
    op.create_index(op.f('ix_voca_word'), 'voca', ['word'], unique=False)
    op.create_table('user_voca_association',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('quiz_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['voca.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.add_column('users', sa.Column('exp', sa.Integer(), nullable=True))
    op.drop_column('users', 'ranking')
    op.drop_column('users', 'ranking_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ranking_score', sa.FLOAT(), nullable=True))
    op.add_column('users', sa.Column('ranking', sa.INTEGER(), nullable=True))
    op.drop_column('users', 'exp')
    op.drop_table('user_voca_association')
    op.drop_index(op.f('ix_voca_word'), table_name='voca')
    op.drop_index(op.f('ix_voca_id'), table_name='voca')
    op.drop_table('voca')
    # ### end Alembic commands ###
