"""empty message

Revision ID: f7be436df657
Revises: 9e8415f7ba23
Create Date: 2024-07-30 20:35:49.956824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7be436df657'
down_revision: Union[str, None] = '9e8415f7ba23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lectures', sa.Column('image', sa.String(), nullable=True))
    op.add_column('lectures', sa.Column('description', sa.Text(), nullable=True))
    op.create_index(op.f('ix_lectures_description'), 'lectures', ['description'], unique=False)
    op.create_index(op.f('ix_lectures_image'), 'lectures', ['image'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lectures_image'), table_name='lectures')
    op.drop_index(op.f('ix_lectures_description'), table_name='lectures')
    op.drop_column('lectures', 'description')
    op.drop_column('lectures', 'image')
    # ### end Alembic commands ###
